[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/mensagens"
  to = "/.netlify/functions/mensagens"
  status = 200

[[redirects]]
  from = "/api/mensagens/*"
  to = "/.netlify/functions/mensagens"
  status = 200
